import { Button } from "../components/Button";
import { PageMeta } from "../components/PageMeta";
import { WaitlistForm } from "../components/WaitlistForm";

const capabilities = [
  { icon: "◎", title: "Organization & staff", text: "Create a company workspace, invite staff, and manage who can prepare and support customer visits." },
  { icon: "↗", title: "Customer visit preparation", text: "Set up each customer session in advance, then assign the visit credit or entitlement that unlocks their guide." },
  { icon: "⌁", title: "Simple visitor access", text: "Send each traveler a unique access link so they can open their prepared itinerary without a complicated setup process." },
  { icon: "◇", title: "A recognizable welcome", text: "Add company branding and a tailored welcome message so the guide feels connected to the service your customer booked." },
  { icon: "⊕", title: "Tour-specific instructions", text: "Keep meeting points, transportation details, and special instructions beside the prepared customer visit." },
  { icon: "◫", title: "Coordinated operations", text: "Give authorized staff a shared view of active visits, progress, itinerary adjustments, and internal operational notes." },
];

export function CompaniesPage() {
  return <>
    <PageMeta title="For travel companies" description="Planned Park Pilot tools for travel agencies and tour operators to prepare, brand, distribute, and support personalized digital park guides." />
    <section className="companies-hero"><div className="container companies-hero-grid">
      <div className="companies-hero-copy"><span className="companies-planned"><span>PLANNED</span> Future company capabilities</span><span className="kicker">FOR TRAVEL AGENCIES & TOUR OPERATORS</span><h1>Give every traveler a guide prepared for them.</h1><p>Park Pilot is exploring a company platform for delivering branded, personalized digital park guidance—without staff manually planning and monitoring every customer visit.</p><div className="hero-actions hero-actions--left"><Button to="#company-interest">Register company interest</Button><Button to="/product" variant="secondary">See the visitor experience</Button></div><p className="companies-disclaimer">Concept-stage capabilities. Not currently available.</p></div>
      <div className="company-workspace" aria-label="Concept illustration of a tour company workspace"><div className="workspace-top"><div><span className="workspace-logo" aria-hidden="true">N</span><strong>Your travel company</strong></div><span className="concept-chip">CONCEPT</span></div><div className="workspace-body"><nav aria-label="Concept dashboard navigation"><span className="selected">Active visits</span><span>Customers</span><span>Visit credits</span><span>Team</span></nav><div className="workspace-main"><div className="workspace-title"><div><small>THURSDAY · ACTIVE VISITS</small><h2>Customer journeys</h2></div><span className="workspace-count">3 active</span></div>
        <div className="visit-row"><span className="visitor-avatar">AM</span><div><strong>Alvarez family</strong><small>North Park · In progress</small></div><div className="progress"><span><i style={{ width: "64%" }} /></span><small>4 of 7 stops</small></div><em>On plan</em></div>
        <div className="visit-row"><span className="visitor-avatar avatar--yellow">JK</span><div><strong>Jordan & Kai</strong><small>Harbor Park · In progress</small></div><div className="progress"><span><i style={{ width: "42%" }} /></span><small>3 of 8 stops</small></div><em>Updated</em></div>
        <div className="visit-row"><span className="visitor-avatar avatar--coral">RB</span><div><strong>R. Bennett</strong><small>Summit Park · Starts at 10:00</small></div><div className="progress"><span><i style={{ width: "12%" }} /></span><small>Ready to begin</small></div><em>Prepared</em></div>
        <div className="workspace-note"><span aria-hidden="true">i</span><p><strong>Staff note</strong> Transportation pickup remains at the east entrance.</p></div></div></div></div>
    </div></section>

    <section className="company-context"><div className="container"><strong>One operating layer for</strong><span>Preparing visits</span><span>Delivering guidance</span><span>Supporting travelers</span><span>Tracking usage</span></div></section>

    <section className="section company-value"><div className="container"><div className="company-heading-grid"><div><span className="kicker">PERSONAL SERVICE, WITHOUT THE MANUAL LOAD</span><h2>Your expertise gets the customer started. Park Pilot keeps their day moving.</h2></div><p>A company could prepare the visit once, share it directly with the traveler, and retain the visibility needed to help when an exceptional situation calls for human support.</p></div><ol className="company-flow"><li><span>01</span><div><strong>Prepare</strong><p>Create the customer visit, priorities, and practical tour instructions.</p></div></li><li><span>02</span><div><strong>Assign</strong><p>Apply a visit credit and generate a unique visitor access link.</p></div></li><li><span>03</span><div><strong>Guide</strong><p>The traveler follows a live, personalized itinerary throughout the park.</p></div></li><li><span>04</span><div><strong>Support</strong><p>Authorized staff can see progress and step in when truly needed.</p></div></li></ol></div></section>

    <section className="section section--sand"><div className="container"><div className="section-heading"><span className="kicker">PLANNED COMPANY WORKSPACE</span><h2>From booking handoff to park-day support.</h2><p>The proposed tools connect customer preparation, branded delivery, and tour operations in one workflow.</p></div><div className="company-capabilities">{capabilities.map((capability) => <article key={capability.title}><span aria-hidden="true">{capability.icon}</span><h3>{capability.title}</h3><p>{capability.text}</p></article>)}</div></div></section>

    <section className="section section--ink company-ops"><div className="container company-ops-grid"><div><span className="kicker kicker--light">ACTIVE-VISIT OPERATIONS</span><h2>Visibility when support matters. Autonomy when it does not.</h2><p>A planned operations dashboard would help staff understand which customer visits are active and how each itinerary is progressing—without requiring someone to manually monitor every decision.</p><ul className="plain-checks"><li>See active visits and itinerary progress</li><li>Make authorized itinerary adjustments for exceptional situations</li><li>Add internal notes so staff can coordinate support</li><li>Keep customer-facing guidance separate from team context</li></ul><p className="planned-note"><strong>Planned capability:</strong> dashboard access and adjustments would be permission-controlled.</p></div>
      <div className="ops-panel" aria-label="Concept itinerary support panel"><div className="ops-panel-head"><div><small>VISIT SUPPORT · CONCEPT</small><h3>Alvarez family</h3></div><span>In progress</span></div><div className="ops-progress"><div><strong>4 of 7</strong><span>planned stops completed</span></div><span className="progress-track"><i /></span></div><div className="ops-next"><small>CURRENT RECOMMENDATION</small><strong>River Rapids</strong><span>18 min wait · 8 min walk</span></div><div className="ops-actions"><span>Adjust itinerary</span><span>Add internal note</span></div><div className="ops-audit"><span>11:18</span><p><strong>Plan recalculated</strong> Temporary closure accounted for automatically.</p></div></div>
    </div></section>

    <section className="section company-commerce"><div className="container company-commerce-grid"><div><span className="kicker">PLANNED BUSINESS MODEL</span><h2>Access that follows your customer volume.</h2><p>The company offering is expected to support visit-credit bundles for distribution to customers, with optional recurring plans for frequent use. Commercial packaging has not been finalized.</p><Button to="#company-interest" variant="secondary">Share your interest</Button></div><div className="commerce-list"><article><span>01</span><div><h3>Visit-credit bundles</h3><p>Purchase visitor sessions and assign entitlements as customer visits are prepared.</p></div></article><article><span>02</span><div><h3>Optional recurring plans</h3><p>A potential predictable billing option for companies with frequent visitor volume.</p></div></article><article><span>03</span><div><h3>Usage tracking & reporting</h3><p>Review consumed entitlements and visitor usage to manage the account and evaluate value.</p></div></article></div></div></section>

    <section className="company-cta" id="company-interest"><div className="container company-cta-grid"><div><span className="kicker kicker--light">EARLY COMPANY INTEREST</span><h2>Help shape the company experience.</h2><p>If you work with a travel agency or tour operator, join the Park Pilot waitlist for future product updates. Company capabilities are planned and not yet available.</p></div><div><WaitlistForm compact /><p className="company-cta-note">Use your work email if you would like us to understand your company interest. Product updates only.</p></div></div></section>
  </>;
}