import { Button } from "../components/Button";
import { PageMeta } from "../components/PageMeta";
import { WaitlistForm } from "../components/WaitlistForm";
import { useI18n } from "../i18n";

const capabilities = [
  { icon: "◎", title: "Organization & staff", text: "Create a company workspace, invite staff, and manage who can prepare and support customer visits." },
  { icon: "↗", title: "Customer visit preparation", text: "Set up each customer session in advance, then assign the visit credit or entitlement that unlocks their guide." },
  { icon: "⌁", title: "Simple visitor access", text: "Send each traveler a unique access link so they can open their prepared itinerary without a complicated setup process." },
  { icon: "◇", title: "A recognizable welcome", text: "Add company branding and a tailored welcome message so the guide feels connected to the service your customer booked." },
  { icon: "⊕", title: "Tour-specific instructions", text: "Keep meeting points, transportation details, and special instructions beside the prepared customer visit." },
  { icon: "◫", title: "Coordinated operations", text: "Give authorized staff a shared view of active visits, progress, itinerary adjustments, and internal operational notes." },
];

export function CompaniesPage() {
  const { t } = useI18n();
  return <>
    <PageMeta title="For travel companies" description="Planned Park Pilot tools for travel agencies and tour operators to prepare, brand, distribute, and support personalized digital park guides." />
    <section className="companies-hero"><div className="container companies-hero-grid">
      <div className="companies-hero-copy"><span className="companies-planned"><span>{t("PLANNED")}</span>{t("Future company capabilities")}</span><span className="kicker">{t("FOR TRAVEL AGENCIES & TOUR OPERATORS")}</span><h1>{t("Give every traveler a guide prepared for them.")}</h1><p>{t("Park Pilot is exploring a company platform for delivering branded, personalized digital park guidance—without staff manually planning and monitoring every customer visit.")}</p><div className="hero-actions hero-actions--left"><Button to="#company-interest">{t("Register company interest")}</Button><Button to="/product" variant="secondary">{t("See the visitor experience")}</Button></div><p className="companies-disclaimer">{t("Concept-stage capabilities. Not currently available.")}</p></div>
      <div className="company-workspace" aria-label={t("Concept illustration of a tour company workspace")}><div className="workspace-top"><div><span className="workspace-logo" aria-hidden="true">{t("N")}</span><strong>{t("Your travel company")}</strong></div><span className="concept-chip">{t("CONCEPT")}</span></div><div className="workspace-body"><nav aria-label={t("Concept dashboard navigation")}><span className="selected">{t("Active visits")}</span><span>{t("Customers")}</span><span>{t("Visit credits")}</span><span>{t("Team")}</span></nav><div className="workspace-main"><div className="workspace-title"><div><small>{t("THURSDAY · ACTIVE VISITS")}</small><h2>{t("Customer journeys")}</h2></div><span className="workspace-count">{t("3 active")}</span></div>
        <div className="visit-row"><span className="visitor-avatar">{t("AM")}</span><div><strong>{t("Alvarez family")}</strong><small>{t("North Park · In progress")}</small></div><div className="progress"><span><i style={{ width: "64%" }} /></span><small>{t("4 of 7 stops")}</small></div><em>{t("On plan")}</em></div>
        <div className="visit-row"><span className="visitor-avatar avatar--yellow">{t("JK")}</span><div><strong>{t("Jordan & Kai")}</strong><small>{t("Harbor Park · In progress")}</small></div><div className="progress"><span><i style={{ width: "42%" }} /></span><small>{t("3 of 8 stops")}</small></div><em>{t("Updated")}</em></div>
        <div className="visit-row"><span className="visitor-avatar avatar--coral">{t("RB")}</span><div><strong>{t("R. Bennett")}</strong><small>{t("Summit Park · Starts at 10:00")}</small></div><div className="progress"><span><i style={{ width: "12%" }} /></span><small>{t("Ready to begin")}</small></div><em>{t("Prepared")}</em></div>
        <div className="workspace-note"><span aria-hidden="true">{t("i")}</span><p><strong>{t("Staff note")}</strong>{t("Transportation pickup remains at the east entrance.")}</p></div></div></div></div>
    </div></section>

    <section className="company-context"><div className="container"><strong>{t("One operating layer for")}</strong><span>{t("Preparing visits")}</span><span>{t("Delivering guidance")}</span><span>{t("Supporting travelers")}</span><span>{t("Tracking usage")}</span></div></section>

    <section className="section company-value"><div className="container"><div className="company-heading-grid"><div><span className="kicker">{t("PERSONAL SERVICE, WITHOUT THE MANUAL LOAD")}</span><h2>{t("Your expertise gets the customer started. Park Pilot keeps their day moving.")}</h2></div><p>{t("A company could prepare the visit once, share it directly with the traveler, and retain the visibility needed to help when an exceptional situation calls for human support.")}</p></div><ol className="company-flow"><li><span>01</span><div><strong>{t("Prepare")}</strong><p>{t("Create the customer visit, priorities, and practical tour instructions.")}</p></div></li><li><span>02</span><div><strong>{t("Assign")}</strong><p>{t("Apply a visit credit and generate a unique visitor access link.")}</p></div></li><li><span>03</span><div><strong>{t("Guide")}</strong><p>{t("The traveler follows a live, personalized itinerary throughout the park.")}</p></div></li><li><span>04</span><div><strong>{t("Support")}</strong><p>{t("Authorized staff can see progress and step in when truly needed.")}</p></div></li></ol></div></section>

    <section className="section section--sand"><div className="container"><div className="section-heading"><span className="kicker">{t("PLANNED COMPANY WORKSPACE")}</span><h2>{t("From booking handoff to park-day support.")}</h2><p>{t("The proposed tools connect customer preparation, branded delivery, and tour operations in one workflow.")}</p></div><div className="company-capabilities">{capabilities.map((capability) => <article key={capability.title}><span aria-hidden="true">{capability.icon}</span><h3>{t(capability.title)}</h3><p>{t(capability.text)}</p></article>)}</div></div></section>

    <section className="section section--ink company-ops"><div className="container company-ops-grid"><div><span className="kicker kicker--light">{t("ACTIVE-VISIT OPERATIONS")}</span><h2>{t("Visibility when support matters. Autonomy when it does not.")}</h2><p>{t("A planned operations dashboard would help staff understand which customer visits are active and how each itinerary is progressing—without requiring someone to manually monitor every decision.")}</p><ul className="plain-checks"><li>{t("See active visits and itinerary progress")}</li><li>{t("Make authorized itinerary adjustments for exceptional situations")}</li><li>{t("Add internal notes so staff can coordinate support")}</li><li>{t("Keep customer-facing guidance separate from team context")}</li></ul><p className="planned-note"><strong>{t("Planned capability:")}</strong>{t("dashboard access and adjustments would be permission-controlled.")}</p></div>
      <div className="ops-panel" aria-label={t("Concept itinerary support panel")}><div className="ops-panel-head"><div><small>{t("VISIT SUPPORT · CONCEPT")}</small><h3>{t("Alvarez family")}</h3></div><span>{t("In progress")}</span></div><div className="ops-progress"><div><strong>{t("4 of 7")}</strong><span>{t("planned stops completed")}</span></div><span className="progress-track"><i /></span></div><div className="ops-next"><small>{t("CURRENT RECOMMENDATION")}</small><strong>{t("River Rapids")}</strong><span>{t("18 min wait · 8 min walk")}</span></div><div className="ops-actions"><span>{t("Adjust itinerary")}</span><span>{t("Add internal note")}</span></div><div className="ops-audit"><span>11:18</span><p><strong>{t("Plan recalculated")}</strong>{t("Temporary closure accounted for automatically.")}</p></div></div>
    </div></section>

    <section className="section company-commerce"><div className="container company-commerce-grid"><div><span className="kicker">{t("PLANNED BUSINESS MODEL")}</span><h2>{t("Access that follows your customer volume.")}</h2><p>{t("The company offering is expected to support visit-credit bundles for distribution to customers, with optional recurring plans for frequent use. Commercial packaging has not been finalized.")}</p><Button to="#company-interest" variant="secondary">{t("Share your interest")}</Button></div><div className="commerce-list"><article><span>01</span><div><h3>{t("Visit-credit bundles")}</h3><p>{t("Purchase visitor sessions and assign entitlements as customer visits are prepared.")}</p></div></article><article><span>02</span><div><h3>{t("Optional recurring plans")}</h3><p>{t("A potential predictable billing option for companies with frequent visitor volume.")}</p></div></article><article><span>03</span><div><h3>{t("Usage tracking & reporting")}</h3><p>{t("Review consumed entitlements and visitor usage to manage the account and evaluate value.")}</p></div></article></div></div></section>

    <section className="company-cta" id="company-interest"><div className="container company-cta-grid"><div><span className="kicker kicker--light">{t("EARLY COMPANY INTEREST")}</span><h2>{t("Help shape the company experience.")}</h2><p>{t("If you work with a travel agency or tour operator, join the Park Pilot waitlist for future product updates. Company capabilities are planned and not yet available.")}</p></div><div><WaitlistForm compact /><p className="company-cta-note">{t("Use your work email if you would like us to understand your company interest. Product updates only.")}</p></div></div></section>
  </>;
}