import { useState, type FormEvent, type ReactNode } from "react";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../AuthContext";
import { errorText } from "../components/Ui";
import { LanguageSelector, useI18n } from "../i18n";
import { ApiError, post } from "../lib/api";
import type { AuthResponse } from "../types";

function AuthFrame({ label, title, text, children }: { label: string; title: string; text: string; children: ReactNode }) { const { t } = useI18n(); return <main id="main-content" className="auth-page"><section className="auth-brand"><Link to="/login" className="brand"><span className="brand-mark"><i /></span>Park Pilot <em>{t("COMPANY")}</em></Link><div><span>{label}</span><h1>{title}</h1><p>{text}</p></div><small>{t("Operations tools for travel agencies and tour operators.")}</small></section><section className="auth-panel"><LanguageSelector className="language-selector--auth" />{children}</section></main>; }
function Submit({ pending, children }: { pending: boolean; children: ReactNode }) { const { t } = useI18n(); return <button className="btn btn--primary btn--wide" disabled={pending}>{pending ? t("Please wait…") : children}</button>; }
function ErrorBox({ error }: { error: string }) { const { t } = useI18n(); return error ? <div className="auth-error" role="alert"><strong>{t("Request could not be completed")}</strong><p>{error}</p></div> : null; }
export function LoginPage() { const { t } = useI18n(); const { session, login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); if (session) return <Navigate to="/" replace />; const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setPending(true); const data = new FormData(event.currentTarget); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/"); } catch (err) { setError(err instanceof ApiError ? errorText(err, t) : t("Unable to sign in.")); } finally { setPending(false); } }; return <AuthFrame label={t("COMPANY PORTAL")} title={t("Keep every customer visit in view.")} text={t("Sign in to prepare park days, support active travelers, and manage your company access.")}><div className="auth-form-wrap"><span className="auth-kicker">{t("WELCOME BACK")}</span><h2>{t("Sign in to your workspace")}</h2><p>{t("Use your company account credentials.")}</p><form className="form-stack" onSubmit={submit}><label>{t("Email address")}<input name="email" type="email" autoComplete="email" required /></label><label>{t("Password")}<input name="password" type="password" autoComplete="current-password" required /></label><ErrorBox error={error} /><Submit pending={pending}>{t("Sign in")}</Submit></form><p className="auth-link">{t("Starting a new company?")} <Link to="/bootstrap">{t("Create the first workspace")}</Link></p></div></AuthFrame>; }
export function BootstrapPage() { const { t } = useI18n(); const { establish } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setPending(true); const value = Object.fromEntries(new FormData(event.currentTarget)); try { establish(await post<AuthResponse>("/auth/bootstrap", value, false)); navigate("/"); } catch (err) { setError(err instanceof ApiError ? errorText(err, t) : t("Unable to create the workspace.")); } finally { setPending(false); } }; return <AuthFrame label={t("FIRST ORGANIZATION")} title={t("Set up your company workspace.")} text={t("Bootstrap is intended only for the first organization administrator in a new environment.")}><div className="auth-form-wrap"><span className="auth-kicker">{t("INITIAL SETUP")}</span><h2>{t("Create the organization")}</h2><form className="form-stack" onSubmit={submit}><label>{t("Organization name")}<input name="organizationName" autoComplete="organization" required /></label><label>{t("Administrator email")}<input name="email" type="email" autoComplete="email" required /></label><label>{t("Password")}<input name="password" type="password" minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,}" autoComplete="new-password" required /><small>{t("At least 12 characters with uppercase, lowercase, a number, and a symbol.")}</small></label><ErrorBox error={error} /><Submit pending={pending}>{t("Create workspace")}</Submit></form><p className="auth-link"><Link to="/login">{t("Back to sign in")}</Link></p></div></AuthFrame>; }
export function AcceptInvitationPage() { const { t } = useI18n(); const [params] = useSearchParams(); const token = params.get("token"); const { establish } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!token) return; setPending(true); setError(""); const data = new FormData(event.currentTarget); try { establish(await post<AuthResponse>("/auth/invitations/accept", { token, password: data.get("password") }, false)); navigate("/"); } catch (err) { setError(err instanceof ApiError ? errorText(err, t) : t("Unable to accept invitation.")); } finally { setPending(false); } }; return <AuthFrame label={t("TEAM INVITATION")} title={t("Join your Park Pilot team.")} text={t("Choose a secure password to activate the company account connected to this invitation.")}><div className="auth-form-wrap"><span className="auth-kicker">{t("ACCEPT INVITATION")}</span><h2>{t("Finish account setup")}</h2>{token ? <form className="form-stack" onSubmit={submit}><label>{t("Create password")}<input name="password" type="password" minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,}" autoComplete="new-password" required /><small>{t("At least 12 characters with uppercase, lowercase, a number, and a symbol.")}</small></label><ErrorBox error={error} /><Submit pending={pending}>{t("Accept invitation")}</Submit></form> : <ErrorBox error={t("This invitation link is missing its token. Request a new link from your organization administrator.")} />}</div></AuthFrame>; }
