import { useState, type FormEvent } from "react";
import { Link, Navigate, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../AuthContext";
import { ApiError, post } from "../lib/api";
import type { AuthResponse } from "../types";

function AuthFrame({ label, title, text, children }: { label: string; title: string; text: string; children: React.ReactNode }) { return <main className="auth-page"><section className="auth-brand"><Link to="/login" className="brand"><span className="brand-mark"><i /></span>Park Pilot <em>Company</em></Link><div><span>{label}</span><h1>{title}</h1><p>{text}</p></div><small>Operations tools for travel agencies and tour operators.</small></section><section className="auth-panel">{children}</section></main>; }
function Submit({ pending, children }: { pending: boolean; children: React.ReactNode }) { return <button className="btn btn--primary btn--wide" disabled={pending}>{pending ? "Please wait…" : children}</button>; }
function ErrorBox({ error }: { error: string }) { return error ? <div className="auth-error" role="alert"><strong>Request could not be completed</strong><p>{error}</p></div> : null; }

export function LoginPage() {
  const { session, login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  if (session) return <Navigate to="/" replace />;
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setPending(true); const data = new FormData(event.currentTarget); try { await login(String(data.get("email")), String(data.get("password"))); navigate("/"); } catch (err) { setError(err instanceof ApiError ? err.info.detail : "Unable to sign in."); } finally { setPending(false); } };
  return <AuthFrame label="COMPANY PORTAL" title="Keep every customer visit in view." text="Sign in to prepare park days, support active travelers, and manage your company access."><div className="auth-form-wrap"><span className="auth-kicker">WELCOME BACK</span><h2>Sign in to your workspace</h2><p>Use your company account credentials.</p><form className="form-stack" onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete="current-password" required /></label><ErrorBox error={error} /><Submit pending={pending}>Sign in</Submit></form><p className="auth-link">Starting a new company? <Link to="/bootstrap">Create the first workspace</Link></p></div></AuthFrame>;
}

export function BootstrapPage() {
  const { establish } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setPending(true); const value = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await post<AuthResponse>("/auth/bootstrap", value, false); establish(result); navigate("/"); } catch (err) { setError(err instanceof ApiError ? err.info.detail : "Unable to create the workspace."); } finally { setPending(false); } };
  return <AuthFrame label="FIRST ORGANIZATION" title="Set up your company workspace." text="Bootstrap is intended only for the first organization administrator in a new environment."><div className="auth-form-wrap"><span className="auth-kicker">INITIAL SETUP</span><h2>Create the organization</h2><form className="form-stack" onSubmit={submit}><label>Organization name<input name="organizationName" autoComplete="organization" required /></label><label>Administrator email<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,}" autoComplete="new-password" required /><small>At least 12 characters with uppercase, lowercase, a number, and a symbol.</small></label><ErrorBox error={error} /><Submit pending={pending}>Create workspace</Submit></form><p className="auth-link"><Link to="/login">Back to sign in</Link></p></div></AuthFrame>;
}

export function AcceptInvitationPage() {
  const [params] = useSearchParams(); const token = params.get("token"); const { establish } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!token) return; setPending(true); setError(""); const data = new FormData(event.currentTarget); try { const result = await post<AuthResponse>("/auth/invitations/accept", { token, password: data.get("password") }, false); establish(result); navigate("/"); } catch (err) { setError(err instanceof ApiError ? err.info.detail : "Unable to accept invitation."); } finally { setPending(false); } };
  return <AuthFrame label="TEAM INVITATION" title="Join your Park Pilot team." text="Choose a secure password to activate the company account connected to this invitation."><div className="auth-form-wrap"><span className="auth-kicker">ACCEPT INVITATION</span><h2>Finish account setup</h2>{token ? <form className="form-stack" onSubmit={submit}><label>Create password<input name="password" type="password" minLength={12} pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{12,}" autoComplete="new-password" required /><small>At least 12 characters with uppercase, lowercase, a number, and a symbol.</small></label><ErrorBox error={error} /><Submit pending={pending}>Accept invitation</Submit></form> : <ErrorBox error="This invitation link is missing its token. Request a new link from your organization administrator." />}</div></AuthFrame>;
}
