import { useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { Modal } from "../components/Modal";
import { ApiMessage, Empty, ErrorState, Loading, PageHeader, errorText, formObject } from "../components/Ui";
import { localizedValue, useI18n } from "../i18n";
import { post, put } from "../lib/api";
import { asList, dateText, initials, text } from "../lib/format";
import { useApiData } from "../lib/useApiData";
import type { Entity } from "../types";
export function CustomersPage() { const { t, locale, number } = useI18n(); const { data, loading, error, refresh } = useApiData<unknown>("/customers"); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<Entity | null>(); const [message, setMessage] = useState(""); const customers = asList(data, ["customers"]).filter(item => JSON.stringify(item).toLowerCase().includes(query.toLowerCase())); return <><PageHeader eyebrow={t("CUSTOMER DIRECTORY")} title={t("Customers")} description={t("Customer profiles available to your organization.")} action={<button className="btn btn--primary" onClick={() => setEditing({})}>{t("+ Add customer")}</button>} /><div className="toolbar"><label className="search"><span aria-hidden="true">⌕</span><span className="sr-only">{t("Search customers")}</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t("Search name or email")} /></label><span>{t("{count} shown", { count: number(customers.length) })}</span></div><ApiMessage success={message} />{loading ? <Loading label={t("Loading customers")} /> : error ? <ErrorState message={error} retry={refresh} /> : customers.length ? <section className="panel"><div className="table-scroll"><table><thead><tr><th>{t("Customer")}</th><th>{t("Contact")}</th><th>{t("Upcoming visit")}</th><th>{t("Status")}</th><th><span className="sr-only">{t("Actions")}</span></th></tr></thead><tbody>{customers.map((customer, index) => <tr key={text(customer.id, String(index))}><td><div className="identity"><span>{initials(customer.name ?? customer.fullName)}</span><div><strong>{text(customer.name ?? customer.fullName, t("Unnamed customer"))}</strong><small>{text(customer.reference ?? customer.externalReference, t("No reference"))}</small></div></div></td><td><strong>{text(customer.email)}</strong><small>{text(customer.phone, t("No phone"))}</small></td><td>{dateText(customer.nextVisitDate, locale)}</td><td>{localizedValue(customer.status ?? "Active", t)}</td><td className="actions">{customer.id && <Link to={`/customers/${customer.id}`}>{t("Open")}</Link>}<button onClick={() => setEditing(customer)}>{t("Edit")}</button>{customer.id && <Link to={`/visits?customerId=${customer.id}`}>{t("Visits")}</Link>}</td></tr>)}</tbody></table></div></section> : <Empty title={t("No customers found")} message={query ? t("Try a different search.") : t("Add the first customer to begin preparing a visit.")} action={!query && <button className="btn btn--primary" onClick={() => setEditing({})}>{t("Add customer")}</button>} />}{editing !== undefined && <CustomerForm customer={editing ?? {}} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); setMessage(t("Customer saved.")); void refresh(); }} />}</>; }
function CustomerForm({ customer, onClose, onSaved }: { customer: Entity; onClose: () => void; onSaved: () => void }) { const { t } = useI18n(); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); setError(""); try { const value = formObject(event); customer.id ? await put(`/customers/${customer.id}`, value) : await post("/customers", value); onSaved(); } catch (err) { setError(errorText(err, t)); } finally { setPending(false); } }; return <Modal title={customer.id ? t("Edit customer") : t("Add customer")} onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="span-2">{t("Full name")}<input name="name" defaultValue={text(customer.name ?? customer.fullName, "")} required /></label><label>{t("Email")}<input name="email" type="email" defaultValue={text(customer.email, "")} /></label><label>{t("Phone")}<input name="phone" type="tel" defaultValue={text(customer.phone, "")} /></label><label className="span-2">{t("External reference")}<input name="externalReference" defaultValue={text(customer.externalReference ?? customer.reference, "")} /></label><label className="span-2">{t("Customer context")}<textarea name="notes" defaultValue={text(customer.notes, "")} rows={3} /></label><ApiMessage error={error} /><div className="form-actions span-2"><button type="button" className="btn btn--ghost" onClick={onClose}>{t("Cancel")}</button><button className="btn btn--primary" disabled={pending}>{pending ? t("Saving…") : t("Save customer")}</button></div></form></Modal>; }
