import { useState, type FormEvent } from "react";
import { ApiMessage, Empty, ErrorState, Loading, PageHeader, Status, errorText } from "../components/Ui";
import { localizedValue, useI18n } from "../i18n";
import { post, put } from "../lib/api";
import { asList, dateText, initials, text } from "../lib/format";
import { useApiData } from "../lib/useApiData";

const roles=["Owner","Administrator","Planner","Support"];
export function TeamPage(){const {t,locale}=useI18n();const team=useApiData<unknown>("/team");const pendingInvites=useApiData<unknown>("/team/invitations");const [message,setMessage]=useState("");const [error,setError]=useState("");const [pending,setPending]=useState(false);const [invitationUrl,setInvitationUrl]=useState("");const [notificationId,setNotificationId]=useState("");const members=asList(team.data,["members","staff","team"]);const invitations=asList(pendingInvites.data,["invitations"]);
 const invite=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setPending(true);setError("");setInvitationUrl("");const form=new FormData(e.currentTarget);const hours=String(form.get("expiresInHours")??"");try{const result=await post<Record<string,unknown>>("/team/invitations",{email:form.get("email"),role:form.get("role"),...(hours?{expiresInHours:Number(hours)}:{})});const token=text(result.token,"");setInvitationUrl(token?`${window.location.origin}/accept-invitation?token=${encodeURIComponent(token)}`:"");setNotificationId(text(result.notificationId,""));setMessage(t("Invitation created. Copy and share the link securely; no email has been sent."));e.currentTarget.reset();void pendingInvites.refresh()}catch(err){setError(errorText(err,t))}finally{setPending(false)}};
 const role=async(id:string,value:string)=>{try{await put(`/team/${id}/role`,{role:value});setMessage(t("Role updated."));void team.refresh()}catch(err){setError(errorText(err,t))}};const deactivate=async(id:string)=>{try{await post(`/team/${id}/deactivate`);setMessage(t("Team member deactivated."));void team.refresh()}catch(err){setError(errorText(err,t))}};
 return <><PageHeader eyebrow={t("ACCESS MANAGEMENT")} title={t("Team")} description={t("Invite staff and control access to customer operations.")}/><ApiMessage error={error} success={message}/>{invitationUrl&&<section className="secret-card" role="status"><span>{t("INVITATION LINK · COPY NOW")}</span><h2>{t("Share this link securely")}</h2><div><code>{invitationUrl}</code><button onClick={()=>void navigator.clipboard.writeText(invitationUrl)}>{t("Copy")}</button></div><p>{notificationId?t("Notification {id} is queued for future dispatch; it has not been sent.",{id:notificationId}):t("Notification delivery has not been confirmed. The invitation has not been claimed as sent.")}</p><button className="close-secret" onClick={()=>setInvitationUrl("")}>{t("I have copied the link")}</button></section>}
 <div className="two-column"><section className="panel"><div className="panel-head"><div><span>{t("STAFF DIRECTORY")}</span><h2>{t("Team members")}</h2></div></div>{team.loading?<Loading/>:team.error?<ErrorState message={team.error} retry={team.refresh}/>:members.length?<div className="table-scroll"><table><thead><tr><th>{t("Staff member")}</th><th>{t("Role")}</th><th>{t("Status")}</th><th>{t("Actions")}</th></tr></thead><tbody>{members.map((m,i)=><tr key={text(m.id,String(i))}><td><div className="identity"><span>{initials(m.name??m.email)}</span><div><strong>{text(m.name??m.email)}</strong><small>{text(m.email,"")}</small></div></div></td><td><select aria-label={t("Role for {name}",{name:text(m.name??m.email)})} defaultValue={text(m.role,"Support")} onChange={(e)=>m.id&&void role(String(m.id),e.target.value)}>{roles.map(r=><option key={r} value={r}>{localizedValue(r,t)}</option>)}</select></td><td><Status value={m.status??"Active"}/></td><td><button className="table-action danger" onClick={()=>m.id&&void deactivate(String(m.id))}>{t("Deactivate")}</button></td></tr>)}</tbody></table></div>:<Empty title={t("No team returned")} message={t("Staff members will appear when returned by the API.")}/>}</section>
 <aside className="panel invite-panel"><div className="panel-head"><div><span>{t("ADD STAFF")}</span><h2>{t("Create invitation")}</h2></div></div><form className="form-stack" onSubmit={invite}><label>{t("Email address")}<input name="email" type="email" required/></label><label>{t("Role")}<select name="role">{roles.filter(r=>r!=="Owner").map(r=><option key={r} value={r}>{localizedValue(r,t)}</option>)}</select></label><label>{t("Expires in hours (optional)")}<input name="expiresInHours" type="number" min="1"/></label><button className="btn btn--primary" disabled={pending}>{pending?t("Creating…"):t("Create invitation")}</button><small>{t("The backend may queue a notification for future dispatch. This portal does not claim that email is sent.")}</small></form></aside></div>
 <section className="panel below-panel"><div className="panel-head"><div><span>{t("AWAITING ACCEPTANCE")}</span><h2>{t("Pending invitations")}</h2></div></div>{pendingInvites.loading?<Loading/>:invitations.length?<div className="table-scroll"><table><thead><tr><th>{t("Email")}</th><th>{t("Role")}</th><th>{t("Expires")}</th><th>{t("Status")}</th></tr></thead><tbody>{invitations.map((item,i)=><tr key={text(item.id,String(i))}><td>{text(item.email)}</td><td>{localizedValue(item.role,t)}</td><td>{dateText(item.expiresAt,locale)}</td><td><Status value={item.status??"Pending"}/></td></tr>)}</tbody></table></div>:<Empty title={t("No pending invitations")} message={t("Pending invitations will appear if provided by the API.")}/>}</section></>;
}