import { useState, type FormEvent } from "react";
import { ApiMessage, Empty, ErrorState, Loading, PageHeader, Status, errorText } from "../components/Ui";
import { post, put } from "../lib/api";
import { asList, dateText, initials, text } from "../lib/format";
import { useApiData } from "../lib/useApiData";

const roles=["Owner","Administrator","Planner","Support"];
export function TeamPage(){const team=useApiData<unknown>("/team");const pendingInvites=useApiData<unknown>("/team/invitations");const [message,setMessage]=useState("");const [error,setError]=useState("");const [pending,setPending]=useState(false);const [invitationUrl,setInvitationUrl]=useState("");const [notificationId,setNotificationId]=useState("");const members=asList(team.data,["members","staff","team"]);const invitations=asList(pendingInvites.data,["invitations"]);
 const invite=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setPending(true);setError("");setInvitationUrl("");const form=new FormData(e.currentTarget);const hours=String(form.get("expiresInHours")??"");try{const result=await post<Record<string,unknown>>("/team/invitations",{email:form.get("email"),role:form.get("role"),...(hours?{expiresInHours:Number(hours)}:{})});const token=text(result.token,"");setInvitationUrl(token?`${window.location.origin}/accept-invitation?token=${encodeURIComponent(token)}`:"");setNotificationId(text(result.notificationId,""));setMessage("Invitation created. Copy and share the link securely; no email has been sent.");e.currentTarget.reset();void pendingInvites.refresh()}catch(err){setError(errorText(err))}finally{setPending(false)}};
 const role=async(id:string,value:string)=>{try{await put(`/team/${id}/role`,{role:value});setMessage("Role updated.");void team.refresh()}catch(err){setError(errorText(err))}};const deactivate=async(id:string)=>{try{await post(`/team/${id}/deactivate`);setMessage("Team member deactivated.");void team.refresh()}catch(err){setError(errorText(err))}};
 return <><PageHeader eyebrow="ACCESS MANAGEMENT" title="Team" description="Invite staff and control access to customer operations."/><ApiMessage error={error} success={message}/>{invitationUrl&&<section className="secret-card" role="status"><span>INVITATION LINK · COPY NOW</span><h2>Share this link securely</h2><div><code>{invitationUrl}</code><button onClick={()=>void navigator.clipboard.writeText(invitationUrl)}>Copy</button></div><p>{notificationId?`Notification ${notificationId} is queued for future dispatch; it has not been sent.`:"Notification delivery has not been confirmed. The invitation has not been claimed as sent."}</p><button className="close-secret" onClick={()=>setInvitationUrl("")}>I have copied the link</button></section>}
 <div className="two-column"><section className="panel"><div className="panel-head"><div><span>STAFF DIRECTORY</span><h2>Team members</h2></div></div>{team.loading?<Loading/>:team.error?<ErrorState message={team.error} retry={team.refresh}/>:members.length?<div className="table-scroll"><table><thead><tr><th>Staff member</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{members.map((m,i)=><tr key={text(m.id,String(i))}><td><div className="identity"><span>{initials(m.name??m.email)}</span><div><strong>{text(m.name??m.email)}</strong><small>{text(m.email,"")}</small></div></div></td><td><select aria-label={`Role for ${text(m.name??m.email)}`} defaultValue={text(m.role,"Support")} onChange={(e)=>m.id&&void role(String(m.id),e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></td><td><Status value={m.status??"Active"}/></td><td><button className="table-action danger" onClick={()=>m.id&&void deactivate(String(m.id))}>Deactivate</button></td></tr>)}</tbody></table></div>:<Empty title="No team returned" message="Staff members will appear when returned by the API."/>}</section>
 <aside className="panel invite-panel"><div className="panel-head"><div><span>ADD STAFF</span><h2>Create invitation</h2></div></div><form className="form-stack" onSubmit={invite}><label>Email address<input name="email" type="email" required/></label><label>Role<select name="role">{roles.filter(r=>r!=="Owner").map(r=><option key={r}>{r}</option>)}</select></label><label>Expires in hours (optional)<input name="expiresInHours" type="number" min="1"/></label><button className="btn btn--primary" disabled={pending}>{pending?"Creating…":"Create invitation"}</button><small>The backend may queue a notification for future dispatch. This portal does not claim that email is sent.</small></form></aside></div>
 <section className="panel below-panel"><div className="panel-head"><div><span>AWAITING ACCEPTANCE</span><h2>Pending invitations</h2></div></div>{pendingInvites.loading?<Loading/>:invitations.length?<div className="table-scroll"><table><thead><tr><th>Email</th><th>Role</th><th>Expires</th><th>Status</th></tr></thead><tbody>{invitations.map((item,i)=><tr key={text(item.id,String(i))}><td>{text(item.email)}</td><td>{text(item.role)}</td><td>{dateText(item.expiresAt)}</td><td><Status value={item.status??"Pending"}/></td></tr>)}</tbody></table></div>:<Empty title="No pending invitations" message="Pending invitations will appear if provided by the API."/>}</section></>;
}