import { useState, type FormEvent } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { Modal } from "../components/Modal";
import { ApiMessage, Empty, ErrorState, Loading, PageHeader, Status, errorText, formObject } from "../components/Ui";
import { post, put } from "../lib/api";
import { asList, dateText, text } from "../lib/format";
import { useApiData } from "../lib/useApiData";
import type { Entity } from "../types";

export function VisitsPage() {
  const [params] = useSearchParams(); const customerFilter = params.get("customerId"); const { data, loading, error, refresh } = useApiData<unknown>("/visits"); const customersState = useApiData<unknown>("/customers"); const [editing, setEditing] = useState<Entity | null | undefined>(params.get("new") ? {} : undefined); const [status, setStatus] = useState(params.get("status") ?? "all"); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const visits = asList(data, ["visits"]).filter((visit) => (status === "all" || text(visit.status, "").toLowerCase() === status.toLowerCase()) && (!customerFilter || text(visit.customerId, "") === customerFilter) && JSON.stringify(visit).toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="VISIT OPERATIONS" title="Customer visits" description="Prepare, distribute, and support each customer park day." action={<button className="btn btn--primary" onClick={() => setEditing({})}>+ Prepare visit</button>} /><div className="toolbar toolbar--filters"><label className="search"><span>⌕</span><span className="sr-only">Search visits</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customer or park" /></label><label><span className="sr-only">Filter by status</span><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="Active">Active</option><option value="Planned">Planned</option><option value="Completed">Completed</option><option value="Cancelled">Cancelled</option></select></label></div><ApiMessage success={message} />
  {loading ? <Loading label="Loading visits" /> : error ? <ErrorState message={error} retry={refresh} /> : visits.length ? <section className="panel"><div className="table-scroll"><table><thead><tr><th>Customer</th><th>Date & park</th><th>Party</th><th>Progress</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visits.map((visit,i) => <tr key={text(visit.id,String(i))}><td><strong>{text(visit.customerName ?? visit.customer)}</strong><small>{text(visit.reference, "")}</small></td><td><strong>{dateText(visit.visitDate ?? visit.date)}</strong><small>{text(visit.parkName ?? visit.park)}</small></td><td>{text(visit.partySize, "—")}</td><td>{progressText(visit)}</td><td><Status value={visit.status} /></td><td className="actions">{visit.id && <Link to={`/visits/${visit.id}`}>Open</Link>}<button onClick={() => setEditing(visit)}>Edit</button></td></tr>)}</tbody></table></div></section> : <Empty title="No visits match" message="Prepare a visit or adjust the current filters." />}
  {editing !== undefined && <VisitForm visit={editing ?? {}} customers={asList(customersState.data,["customers"])} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); setMessage("Visit saved."); void refresh(); }} />}
  </>;
}

function VisitForm({ visit, customers, onClose, onSaved }: { visit: Entity; customers: Entity[]; onClose: () => void; onSaved: () => void }) { const [pending,setPending]=useState(false); const [error,setError]=useState(""); const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setPending(true);setError("");try{const value=formObject(event);const payload={...value,partySize:Number(value.partySize),completedItemCount:Number(value.completedItemCount),totalItemCount:Number(value.totalItemCount)};visit.id?await put(`/visits/${visit.id}`,payload):await post("/visits",payload);onSaved()}catch(err){setError(errorText(err))}finally{setPending(false)}}; return <Modal title={visit.id?"Edit visit":"Prepare customer visit"} onClose={onClose}><form className="form-grid" onSubmit={submit}><label className="span-2">Customer<select name="customerId" defaultValue={text(visit.customerId,"")} required><option value="">Select customer</option>{customers.map((c,i)=><option key={text(c.id,String(i))} value={text(c.id,"")}>{text(c.name ?? c.fullName)}</option>)}</select></label><label>Visit date<input name="visitDate" type="date" defaultValue={text(visit.visitDate ?? visit.date,"").slice(0,10)} required /></label><label>Park<input name="parkName" defaultValue={text(visit.parkName,"")} required /></label><label>Time zone<input name="timeZone" defaultValue={text(visit.timeZone,Intl.DateTimeFormat().resolvedOptions().timeZone)} required /></label><label>Party size<input name="partySize" type="number" min="1" max="99" defaultValue={text(visit.partySize,"1")} required /></label><label>Status<select name="status" defaultValue={text(visit.status,"Planned")}><option value="Planned">Planned</option><option value="Active">Active</option><option value="Completed">Completed</option><option value="Cancelled">Cancelled</option></select></label><label>Completed items<input name="completedItemCount" type="number" min="0" defaultValue={text(visit.completedItemCount,"0")} required /></label><label>Total items<input name="totalItemCount" type="number" min="0" defaultValue={text(visit.totalItemCount,"0")} required /></label><label>External reference<input name="externalReference" defaultValue={text(visit.externalReference,"")} /></label><label className="span-2">Visitor instructions<textarea name="instructions" rows={3} defaultValue={text(visit.instructions,"")} /></label><label>Meeting point<textarea name="meetingPoint" rows={2} defaultValue={text(visit.meetingPoint,"")} /></label><label>Transportation<textarea name="transportationDetails" rows={2} defaultValue={text(visit.transportationDetails,"")} /></label><ApiMessage error={error} /><div className="form-actions span-2"><button type="button" className="btn btn--ghost" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={pending}>{pending?"Saving…":"Save visit"}</button></div></form></Modal> }

function progressText(visit: Entity): string {
  const completed = Number(visit.completedItemCount ?? 0);
  const total = Number(visit.totalItemCount ?? 0);
  return total > 0
    ? `${Math.round(completed / total * 100)}% (${completed}/${total})`
    : `${completed}/0`;
}
