CREATE TABLE public.parks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_park_id integer NOT NULL UNIQUE,
    name text NOT NULL,
    timezone text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.lands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id bigint NOT NULL REFERENCES public.parks(id),
    source_land_id integer NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_lands_park_source_land UNIQUE (park_id, source_land_id)
);

CREATE TABLE public.attractions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id bigint NOT NULL REFERENCES public.parks(id),
    current_land_id bigint REFERENCES public.lands(id),
    source_ride_id integer NOT NULL,
    name text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    duration_minutes smallint,
    latitude numeric(9,6),
    longitude numeric(9,6),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_attractions_park_source_ride UNIQUE (park_id, source_ride_id),
    CONSTRAINT ck_attractions_duration CHECK (duration_minutes IS NULL OR duration_minutes > 0),
    CONSTRAINT ck_attractions_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_attractions_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);

CREATE TABLE public.queue_collection_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id bigint NOT NULL REFERENCES public.parks(id),
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    success boolean NOT NULL DEFAULT false,
    error_message text
);

CREATE TABLE public.queue_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_run_id bigint NOT NULL REFERENCES public.queue_collection_runs(id),
    park_id bigint NOT NULL REFERENCES public.parks(id),
    land_id bigint REFERENCES public.lands(id),
    attraction_id bigint NOT NULL REFERENCES public.attractions(id),
    collected_at timestamptz NOT NULL,
    observed_at timestamptz NOT NULL,
    observed_local_date date NOT NULL,
    observed_local_time time NOT NULL,
    observed_local_hour smallint NOT NULL,
    observed_slot_minutes smallint NOT NULL,
    observed_day_of_week smallint NOT NULL,
    is_open boolean NOT NULL,
    wait_minutes smallint,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_queue_observations_hour CHECK (observed_local_hour BETWEEN 0 AND 23),
    CONSTRAINT ck_queue_observations_slot CHECK (observed_slot_minutes BETWEEN 0 AND 1439),
    CONSTRAINT ck_queue_observations_day_of_week CHECK (observed_day_of_week BETWEEN 0 AND 6),
    CONSTRAINT ck_queue_observations_wait_minutes CHECK (wait_minutes IS NULL OR wait_minutes >= 0),
    CONSTRAINT ck_queue_observations_open_wait CHECK (is_open OR wait_minutes IS NULL)
);

CREATE UNIQUE INDEX uq_queue_observations_attraction_observed_at
    ON public.queue_observations (attraction_id, observed_at);
CREATE INDEX ix_queue_observations_park_observed_at
    ON public.queue_observations (park_id, observed_at DESC);
CREATE INDEX ix_queue_observations_attraction_observed_at
    ON public.queue_observations (attraction_id, observed_at DESC)
    INCLUDE (is_open, wait_minutes);
CREATE INDEX ix_queue_observations_park_local_date_hour
    ON public.queue_observations (park_id, observed_local_date, observed_local_hour, attraction_id)
    INCLUDE (wait_minutes) WHERE is_open;
CREATE INDEX ix_queue_observations_weekday_slot
    ON public.queue_observations (park_id, observed_day_of_week, observed_slot_minutes, attraction_id)
    INCLUDE (wait_minutes) WHERE is_open;
CREATE INDEX ix_queue_observations_brin_observed_at
    ON public.queue_observations USING brin (observed_at);
CREATE INDEX ix_collection_runs_park_started_at
    ON public.queue_collection_runs (park_id, started_at DESC);
CREATE INDEX ix_lands_park_active
    ON public.lands (park_id, is_active);
CREATE INDEX ix_attractions_park_active
    ON public.attractions (park_id, is_active);
