CREATE TABLE public.park_route_nodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id bigint NOT NULL REFERENCES public.parks(id),
    name text NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_park_route_nodes_id_park UNIQUE (id, park_id),
    CONSTRAINT ck_park_route_nodes_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_park_route_nodes_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE public.park_route_edges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    park_id bigint NOT NULL REFERENCES public.parks(id),
    from_node_id bigint NOT NULL,
    to_node_id bigint NOT NULL,
    distance_meters integer NOT NULL,
    is_bidirectional boolean NOT NULL DEFAULT true,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_park_route_edges_from_node
        FOREIGN KEY (from_node_id, park_id)
        REFERENCES public.park_route_nodes(id, park_id),
    CONSTRAINT fk_park_route_edges_to_node
        FOREIGN KEY (to_node_id, park_id)
        REFERENCES public.park_route_nodes(id, park_id),
    CONSTRAINT uq_park_route_edges_nodes
        UNIQUE (park_id, from_node_id, to_node_id),
    CONSTRAINT ck_park_route_edges_distinct_nodes
        CHECK (from_node_id <> to_node_id),
    CONSTRAINT ck_park_route_edges_distance
        CHECK (distance_meters > 0)
);

ALTER TABLE public.attractions
ADD COLUMN route_node_id bigint,
ADD CONSTRAINT fk_attractions_route_node
    FOREIGN KEY (route_node_id, park_id)
    REFERENCES public.park_route_nodes(id, park_id);

CREATE INDEX ix_park_route_nodes_active
    ON public.park_route_nodes (park_id, id)
    WHERE is_active;

CREATE INDEX ix_park_route_edges_active_from
    ON public.park_route_edges (park_id, from_node_id)
    INCLUDE (to_node_id, distance_meters, is_bidirectional)
    WHERE is_active;
