import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export const supportedLocales = ['en', 'pt-BR', 'es'] as const
export type Locale = (typeof supportedLocales)[number]

const messages = {
  language:['Language','Idioma','Idioma'], english:['English','English','English'], portuguese:['Português (Brasil)','Português (Brasil)','Português (Brasil)'], spanish:['Español','Español','Español'], appTitle:['Park Queue Intelligence','Inteligência de Filas dos Parques','Inteligencia de Filas de Parques'],
  home:['Park Queue Intelligence home','Início do Park Queue Intelligence','Inicio de Park Queue Intelligence'], brand:['Queue Intelligence','Queue Intelligence','Queue Intelligence'], parkOperations:['Park operations','Operações do parque','Operaciones del parque'], administration:['Administration','Administração','Administración'], visitorDashboard:['Visitor dashboard','Painel do visitante','Panel de visitantes'], serviceOnline:['Data service online','Serviço de dados online','Servicio de datos en línea'],
  liveOperations:['Live operations','Operações ao vivo','Operaciones en vivo'], waitTimes:['Attraction wait times','Tempos de espera das atrações','Tiempos de espera de atracciones'], dashboardDescription:['Monitor current queues and compare three months of historical patterns.','Monitore as filas atuais e compare três meses de padrões históricos.','Supervisa las filas actuales y compara tres meses de patrones históricos.'], viewingPark:['Viewing park','Parque exibido','Parque mostrado'], parkSummary:['Park summary','Resumo do parque','Resumen del parque'], trackedAttractions:['Tracked attractions','Atrações monitoradas','Atracciones supervisadas'], currentlyOpen:['Currently open','Abertas agora','Abiertas ahora'], averageCurrentWait:['Average current wait','Espera média atual','Espera promedio actual'], parkTimezone:['Park timezone','Fuso horário do parque','Zona horaria del parque'],
  dailyComparison:['Daily park comparison','Comparação diária dos parques','Comparación diaria de parques'], averageEachPark:['Average wait across each park','Espera média em cada parque','Espera promedio en cada parque'], dailyDescription:['Each attraction contributes one daily average, regardless of sample count.','Cada atração contribui com uma média diária, independentemente do número de amostras.','Cada atracción aporta un promedio diario, sin importar la cantidad de muestras.'], currentWeek:['Current week','Semana atual','Semana actual'], selectWeek:['Select comparison week','Selecionar semana de comparação','Seleccionar semana de comparación'], previousWeek:['View previous week','Ver semana anterior','Ver semana anterior'], nextWeek:['View next week','Ver próxima semana','Ver semana siguiente'],
  currentConditions:['Current conditions','Condições atuais','Condiciones actuales'], attractionQueues:['Attraction queues','Filas das atrações','Filas de atracciones'], live:['Live','Ao vivo','En vivo'], updated:['Updated {date}','Atualizado em {date}','Actualizado {date}'], filterQueues:['Filter attraction queues','Filtrar filas das atrações','Filtrar filas de atracciones'], land:['Land','Área','Área'], filterLand:['Filter attractions by land','Filtrar atrações por área','Filtrar atracciones por área'], allLands:['All lands','Todas as áreas','Todas las áreas'], attractionName:['Attraction name','Nome da atração','Nombre de la atracción'], filterName:['Filter attractions by name','Filtrar atrações por nome','Filtrar atracciones por nombre'], searchAttractions:['Search attractions','Buscar atrações','Buscar atracciones'], attraction:['Attraction','Atração','Atracción'], wait:['Wait','Espera','Espera'], parkWide:['Park-wide','Todo o parque','Todo el parque'], closed:['Closed','Fechada','Cerrada'], min:['min','min','min'],
  threeMonthTrend:['Three-month trend','Tendência de três meses','Tendencia de tres meses'], selectAttraction:['Select an attraction','Selecione uma atração','Selecciona una atracción'], dailyHistoryAria:['Daily wait-time history for {name}','Histórico diário de espera de {name}','Historial diario de espera de {name}'], typicalDemand:['Typical demand','Demanda típica','Demanda típica'], waitByWeekday:['Wait by weekday and time','Espera por dia e horário','Espera por día y hora'], averages15:['15-minute averages','Médias de 15 minutos','Promedios de 15 minutos'], patternAria:['Average waits by weekday and time for {name}','Esperas médias por dia e horário de {name}','Esperas promedio por día y hora de {name}'], dailyParkAria:['Daily average park wait times from {start} through {end}','Tempos médios diários de espera de {start} até {end}','Tiempos de espera diarios promedio del {start} al {end}'],
  loadingParks:['Loading park intelligence...','Carregando informações dos parques...','Cargando información de parques...'], catalogUnavailable:['The park catalog is unavailable.','O catálogo de parques está indisponível.','El catálogo de parques no está disponible.'], preparingChart:['Preparing chart...','Preparando gráfico...','Preparando gráfico...'], loadingAnalytics:['Loading analytics...','Carregando análises...','Cargando análisis...'], analyticsUnavailable:['Analytics could not be loaded.','Não foi possível carregar as análises.','No se pudieron cargar los análisis.'], notEnoughData:['Not enough observations are available yet.','Ainda não há observações suficientes.','Aún no hay suficientes observaciones.'], currentWaitsUnavailable:['Current waits could not be loaded.','Não foi possível carregar as esperas atuais.','No se pudieron cargar las esperas actuales.'], noObservations:['No attraction observations are available yet.','Ainda não há observações de atrações.','Aún no hay observaciones de atracciones.'], noFilterMatches:['No attractions match the selected filters.','Nenhuma atração corresponde aos filtros.','Ninguna atracción coincide con los filtros.'], loadingWaits:['Loading current attraction waits','Carregando esperas atuais','Cargando esperas actuales'], connectionError:['Connection error','Erro de conexão','Error de conexión'], pleaseWait:['Please wait','Aguarde','Espera'],
  averageMinutes:['Average minutes','Média em minutos','Promedio en minutos'], minutes:['Minutes','Minutos','Minutos'], dailyAverage:['Daily average','Média diária','Promedio diario'], dailyMaximum:['Daily maximum','Máximo diário','Máximo diario'], averageWait:['Average wait','Espera média','Espera promedio'], attractionsCount:['{count} attractions','{count} atrações','{count} atracciones'], samplesCount:['{count} samples','{count} amostras','{count} muestras'], sunday:['Sunday','Domingo','Domingo'], monday:['Monday','Segunda-feira','Lunes'], tuesday:['Tuesday','Terça-feira','Martes'], wednesday:['Wednesday','Quarta-feira','Miércoles'], thursday:['Thursday','Quinta-feira','Jueves'], friday:['Friday','Sexta-feira','Viernes'], saturday:['Saturday','Sábado','Sábado'],
  planVisit:['Plan a visit','Planejar uma visita','Planear una visita'], visitPlanner:['Visit planner','Planejador de visita','Planificador de visita'], backToWaitTimes:['Wait times','Tempos de espera','Tiempos de espera'], skipToContent:['Skip to content','Pular para o conteúdo','Saltar al contenido'],
  visitSetupEyebrow:['Start your park day','Comece seu dia no parque','Comienza tu día en el parque'], visitSetupTitle:['Plan your visit','Planeje sua visita','Planea tu visita'], visitSetupDescription:["Tell us when you will be at the park and who is coming. We’ll use these details to shape a realistic day.",'Informe quando você estará no parque e quem irá com você. Usaremos esses dados para criar um dia realista.','Dinos cuándo estarás en el parque y quién irá contigo. Usaremos estos datos para crear un día realista.'], planningProgress:['Planning progress','Progresso do planejamento','Progreso de planificación'], visitDetailsStep:['Visit details','Detalhes da visita','Detalles de la visita'], prioritiesStep:['Attraction priorities','Prioridades de atrações','Prioridades de atracciones'],
  visitTipTitle:['A little timing goes a long way','Um pouco de planejamento faz diferença','Un poco de planificación marca la diferencia'], visitTip:["Choose the times you realistically expect to enter and leave. You can edit everything before building your itinerary.",'Escolha os horários realistas em que espera entrar e sair. Você pode editar tudo antes de criar seu roteiro.','Elige las horas reales a las que esperas entrar y salir. Puedes editar todo antes de crear tu itinerario.'],
  scheduleTitle:['When are you visiting?','Quando será sua visita?','¿Cuándo será tu visita?'], scheduleDescription:["Your visit window helps us keep every recommendation within your park day.",'O período da visita nos ajuda a manter cada recomendação dentro do seu dia no parque.','El horario de tu visita nos ayuda a mantener cada recomendación dentro de tu día en el parque.'], visitDate:['Visit date','Data da visita','Fecha de visita'], visitDateHelp:['Today or any future date','Hoje ou qualquer data futura','Hoy o cualquier fecha futura'], arrivalTime:['Arrival time','Horário de chegada','Hora de llegada'], arrivalTimeHelp:['When you expect to enter the park','Quando você espera entrar no parque','Cuando esperas entrar al parque'], departureTime:['Departure time','Horário de saída','Hora de salida'], departureTimeHelp:['Must be later than your arrival','Deve ser posterior à chegada','Debe ser posterior a tu llegada'], partySize:['Party size','Tamanho do grupo','Tamaño del grupo'], partySizeHelp:['Between {min} and {max} people','Entre {min} e {max} pessoas','Entre {min} y {max} personas'], decreaseParty:['Remove one person','Remover uma pessoa','Quitar una persona'], increaseParty:['Add one person','Adicionar uma pessoa','Añadir una persona'], continuePlanning:['Continue','Continuar','Continuar'], visitNotSaved:["Your details stay only in this planning session.",'Seus dados ficam apenas nesta sessão de planejamento.','Tus datos solo permanecen en esta sesión de planificación.'],
  formErrorTitle:['Check the highlighted details','Verifique os dados destacados','Revisa los datos resaltados'], visitDateRequired:['Choose a visit date.','Escolha uma data para a visita.','Elige una fecha de visita.'], visitDateInvalid:['Enter a valid visit date.','Insira uma data de visita válida.','Introduce una fecha de visita válida.'], visitDatePast:["Your visit date can’t be in the past.",'A data da visita não pode estar no passado.','La fecha de visita no puede estar en el pasado.'], arrivalRequired:['Choose an arrival time.','Escolha um horário de chegada.','Elige una hora de llegada.'], arrivalInvalid:['Enter a valid arrival time.','Insira um horário de chegada válido.','Introduce una hora de llegada válida.'], departureRequired:['Choose a departure time.','Escolha um horário de saída.','Elige una hora de salida.'], departureInvalid:['Enter a valid departure time.','Insira um horário de saída válido.','Introduce una hora de salida válida.'], departureAfterArrival:['Departure must be later than arrival.','A saída deve ser posterior à chegada.','La salida debe ser posterior a la llegada.'], partyRequired:['Enter your party size.','Informe o tamanho do grupo.','Introduce el tamaño del grupo.'], partyWholeNumber:['Party size must be a whole number.','O tamanho do grupo deve ser um número inteiro.','El tamaño del grupo debe ser un número entero.'], partyRange:['Party size must be between {min} and {max}.','O grupo deve ter entre {min} e {max} pessoas.','El grupo debe tener entre {min} y {max} personas.'],
  detailsReadyEyebrow:['Visit details complete','Detalhes da visita concluídos','Detalles de la visita completos'], detailsReadyTitle:["You’re ready to choose attractions",'Tudo pronto para escolher as atrações','Todo listo para elegir atracciones'], detailsReadyDescription:["Your visit window is set. Next, choose the attractions that matter to your group.",'O período da sua visita está definido. Agora escolha as atrações que mais importam para o seu grupo.','El horario de tu visita está definido. Ahora elige las atracciones que más le importan a tu grupo.'], visitSummary:['Visit summary','Resumo da visita','Resumen de la visita'], visitWindow:['Time in park','Tempo no parque','Tiempo en el parque'], peopleCount:['{count} people','{count} pessoas','{count} personas'], editVisitDetails:['Edit visit details','Editar detalhes da visita','Editar detalles de la visita'], viewLiveWaitTimes:['View live wait times','Ver tempos de espera ao vivo','Ver tiempos de espera en vivo'],
  continueToPriorities:['Choose attractions','Escolher atrações','Elegir atracciones'], chooseAttractionPriorities:['Choose attraction priorities','Escolher prioridades das atrações','Elegir prioridades de atracciones'],
  priorityEyebrow:['Shape your park day','Defina seu dia no parque','Define tu día en el parque'], priorityPageTitle:['Choose your attractions','Escolha suas atrações','Elige tus atracciones'], priorityDescription:['Tell us what matters most. Every attraction can have one priority, and you can change your choices at any time.','Conte o que mais importa. Cada atração pode ter uma prioridade, e você pode alterar suas escolhas a qualquer momento.','Dinos qué es lo más importante. Cada atracción puede tener una prioridad y puedes cambiar tus elecciones cuando quieras.'], priorityTipTitle:['Start with your non-negotiables','Comece pelo que é indispensável','Empieza por lo imprescindible'], priorityTip:['Mark a few Must Do attractions first, then use Would Like for flexible additions. Skip removes an attraction from the future itinerary.','Marque primeiro algumas atrações indispensáveis e use Gostaria para opções flexíveis. Ignorar remove uma atração do roteiro futuro.','Marca primero algunas atracciones imprescindibles y usa Me gustaría para opciones flexibles. Omitir elimina una atracción del futuro itinerario.'],
  visitContext:['Your visit','Sua visita','Tu visita'], editVisit:['Edit','Editar','Editar'], catalogChoices:['Park catalog','Catálogo do parque','Catálogo del parque'], choosePark:['Choose a park','Escolha um parque','Elige un parque'], chooseParkHelp:['Priorities are kept separately for each park in this planning session.','As prioridades são mantidas separadamente para cada parque nesta sessão de planejamento.','Las prioridades se guardan por separado para cada parque en esta sesión de planificación.'], parkChangedStatus:['Now showing {name}.','Exibindo agora {name}.','Mostrando ahora {name}.'], noParksConfigured:['No parks are available for planning yet.','Ainda não há parques disponíveis para planejamento.','Aún no hay parques disponibles para planificar.'],
  prioritySummary:['Priority selection summary','Resumo da seleção de prioridades','Resumen de selección de prioridades'], mustDo:['Must Do','Imperdível','Imprescindible'], wouldLike:['Would Like','Gostaria','Me gustaría'], skip:['Skip','Ignorar','Omitir'], unselected:['Not selected','Não selecionada','Sin seleccionar'],
  suggestionsEyebrow:['Live opportunities','Oportunidades ao vivo','Oportunidades en vivo'], suggestionsTitle:['Good additions right now','Boas opções para adicionar agora','Buenas opciones para añadir ahora'], suggestionsDescription:['These are open attractions you have not selected. Add one only if it fits your day.','Estas são atrações abertas que você não selecionou. Adicione uma somente se fizer sentido para o seu dia.','Estas son atracciones abiertas que no has seleccionado. Añade una solo si encaja en tu día.'], suggestionBadge:['Suggestion · not saved','Sugestão · não salva','Sugerencia · no guardada'], recommendationMethod:['How it works: open, unselected attractions are ranked by the shortest known live wait, then by name. This rule is deterministic—not random or AI-generated.','Como funciona: atrações abertas e não selecionadas são ordenadas pela menor espera conhecida ao vivo e depois pelo nome. A regra é determinística, não aleatória nem gerada por IA.','Cómo funciona: las atracciones abiertas y no seleccionadas se ordenan por la menor espera conocida en vivo y luego por nombre. La regla es determinista, no aleatoria ni generada por IA.'], recommendationKnownWait:['Open with a {count}-minute live wait; lower waits rank first.','Aberta com espera ao vivo de {count} min; esperas menores aparecem primeiro.','Abierta con una espera en vivo de {count} min; las esperas menores aparecen primero.'], recommendationOpenNoWait:['Open now; listed after suggestions with a known live wait.','Aberta agora; aparece após sugestões com espera ao vivo conhecida.','Abierta ahora; aparece después de sugerencias con espera en vivo conocida.'], addWouldLike:['Add as Would Like','Adicionar como Gostaria','Añadir como Me gustaría'], noRecommendations:['There are no open, unselected attractions to suggest right now.','Não há atrações abertas e não selecionadas para sugerir agora.','No hay atracciones abiertas y sin seleccionar para sugerir ahora.'],
  catalogTitle:['Set every priority','Defina cada prioridade','Define cada prioridad'], catalogDescription:['Use the filters to move quickly through the live attraction catalog.','Use os filtros para navegar rapidamente pelo catálogo de atrações ao vivo.','Usa los filtros para recorrer rápidamente el catálogo de atracciones en vivo.'], filters:['Attraction filters','Filtros de atrações','Filtros de atracciones'], prioritySearchLabel:['Search','Buscar','Buscar'], searchPriorityAttractions:['Search by attraction name','Buscar pelo nome da atração','Buscar por nombre de atracción'], showLand:['Show land','Mostrar área','Mostrar área'], showPriority:['Show priority','Mostrar prioridade','Mostrar prioridad'], allPriorities:['All priorities','Todas as prioridades','Todas las prioridades'], setPriorityFor:['Set priority for {name}','Definir prioridade para {name}','Definir prioridad para {name}'], noPriorityMatches:['No attractions match these filters.','Nenhuma atração corresponde a estes filtros.','Ninguna atracción coincide con estos filtros.'],
  priorityUpdated:['{name} is now {priority}.','{name} agora é {priority}.','{name} ahora es {priority}.'], priorityCleared:['Priority removed from {name}.','Prioridade removida de {name}.','Prioridad eliminada de {name}.'], automaticSave:['Choices are saved automatically in this planning session.','As escolhas são salvas automaticamente nesta sessão de planejamento.','Las elecciones se guardan automáticamente en esta sesión de planificación.'], loadingAttractionCatalog:['Loading the live attraction catalog...','Carregando o catálogo de atrações ao vivo...','Cargando el catálogo de atracciones en vivo...'], attractionCatalogUnavailable:['The attraction catalog could not be loaded. Your saved choices are still here.','Não foi possível carregar o catálogo de atrações. Suas escolhas salvas continuam aqui.','No se pudo cargar el catálogo de atracciones. Tus elecciones guardadas siguen aquí.'], noAttractionsInPark:['This park has no active attractions in the live catalog yet.','Este parque ainda não tem atrações ativas no catálogo ao vivo.','Este parque aún no tiene atracciones activas en el catálogo en vivo.'], openWithoutWait:['Open · wait unavailable','Aberta · espera indisponível','Abierta · espera no disponible'], liveWaitMinutes:['Open · {count} min','Aberta · {count} min','Abierta · {count} min'],
  operationsTooling:['Operations tooling','Ferramentas operacionais','Herramientas operativas'], adminDescription:['Maintain catalog data, monitor collection health, and manage queue observations.','Mantenha os dados do catálogo, monitore a coleta e gerencie observações de filas.','Mantén los datos del catálogo, supervisa la recopilación y administra observaciones de filas.'], workingPark:['Working park','Parque em edição','Parque en edición'], addPark:['Add park','Adicionar parque','Agregar parque'], adminSections:['Administration sections','Seções de administração','Secciones de administración'], operations:['Operations','Operações','Operaciones'], catalog:['Catalog','Catálogo','Catálogo'], observations:['Observations','Observações','Observaciones'], collectionRuns:['Collection runs','Execuções de coleta','Ejecuciones de recopilación'], loadingAdmin:['Loading administration data...','Carregando dados administrativos...','Cargando datos administrativos...'], adminUnavailable:['Administration data could not be loaded.','Não foi possível carregar os dados administrativos.','No se pudieron cargar los datos administrativos.'],
  catalogSetup:['Catalog setup','Configuração do catálogo','Configuración del catálogo'], addSupportedPark:['Add supported park','Adicionar parque compatível','Agregar parque compatible'], externalQueueId:['Use the external Queue-Times park identifier','Use o identificador externo do parque no Queue-Times','Usa el identificador externo del parque en Queue-Times'], parkName:['Park name','Nome do parque','Nombre del parque'], externalParkId:['External park ID','ID externo do parque','ID externo del parque'], timezone:['Timezone','Fuso horário','Zona horaria'], collectionInterval:['Collection interval','Intervalo de coleta','Intervalo de recopilación'], minutesWord:['minutes','minutos','minutos'], startAutomatic:['Start automatic collection','Iniciar coleta automática','Iniciar recopilación automática'], parkActive:['Park visible and active','Parque visível e ativo','Parque visible y activo'], addingPark:['Adding park...','Adicionando parque...','Agregando parque...'],
  collectionHealth:['Collection health','Saúde da coleta','Estado de recopilación'], attentionRequired:['Attention required','Atenção necessária','Requiere atención'], collectionActive:['Collection active','Coleta ativa','Recopilación activa'], collectionPaused:['Collection paused','Coleta pausada','Recopilación pausada'], attractions:['Attractions','Atrações','Atracciones'], lastAttempt:['Last attempt','Última tentativa','Último intento'], lastResult:['Last result','Último resultado','Último resultado'], noRuns:['No runs','Nenhuma execução','Sin ejecuciones'], successful:['Successful','Bem-sucedida','Correcto'], failed:['Failed','Falhou','Fallido'], collecting:['Collecting...','Coletando...','Recopilando...'], collectNow:['Collect now','Coletar agora','Recopilar ahora'], collectHelp:['Runs immediately without changing the automatic schedule.','Executa imediatamente sem alterar a programação automática.','Se ejecuta de inmediato sin cambiar la programación automática.'], configuration:['Configuration','Configuração','Configuración'], parkSettings:['Park settings','Configurações do parque','Configuración del parque'], automaticCollection:['Automatic collection','Coleta automática','Recopilación automática'], saving:['Saving...','Salvando...','Guardando...'], saveSettings:['Save settings','Salvar configurações','Guardar configuración'], parkSaved:['Park settings saved.','Configurações do parque salvas.','Configuración del parque guardada.'], collectionSuccess:['Collection completed successfully.','Coleta concluída com sucesso.','Recopilación completada correctamente.'], never:['Never','Nunca','Nunca'],
  parkStructure:['Park structure','Estrutura do parque','Estructura del parque'], lands:['Lands','Áreas','Áreas'], configured:['{count} configured','{count} configurados','{count} configurados'], addLandPlus:['+ Add land','+ Adicionar área','+ Agregar área'], manualCatalogEntry:['Create a manual catalog entry','Criar uma entrada manual no catálogo','Crear una entrada manual en el catálogo'], source:['Source','Origem','Origen'], active:['Active','Ativo','Activo'], inactive:['Inactive','Inativo','Inactivo'], landName:['Land name','Nome da área','Nombre del área'], externalLandId:['External land ID','ID externo da área','ID externo del área'], landActive:['Land active','Área ativa','Área activa'], saveLand:['Save land','Salvar área','Guardar área'], addLand:['Add land','Adicionar área','Agregar área'], queueCatalog:['Queue catalog','Catálogo de filas','Catálogo de filas'], addAttractionPlus:['+ Add attraction','+ Adicionar atração','+ Agregar atracción'], externalAttractionId:['External attraction ID','ID externo da atração','ID externo de la atracción'], duration:['Duration','Duração','Duración'], latitude:['Latitude','Latitude','Latitud'], longitude:['Longitude','Longitude','Longitud'], attractionActive:['Attraction active','Atração ativa','Atracción activa'], saveAttraction:['Save attraction','Salvar atração','Guardar atracción'], addAttraction:['Add attraction','Adicionar atração','Agregar atracción'],
  lastResort:['Last-resort fallback','Alternativa de último recurso','Alternativa de último recurso'], enterObservation:['Enter queue observation manually','Inserir observação de fila manualmente','Ingresar observación de fila manualmente'], auditableRun:['Creates an auditable manual collection run','Cria uma execução manual auditável','Crea una ejecución manual auditable'], selectAttractionOption:['Select attraction','Selecione a atração','Selecciona la atracción'], observedAt:['Observed at','Observado em','Observado el'], status:['Status','Status','Estado'], open:['Open','Aberta','Abierta'], waitTime:['Wait time','Tempo de espera','Tiempo de espera'], saveObservation:['Save observation','Salvar observação','Guardar observación'], manualHelp:['Use only when automated collection and other sources are unavailable.','Use somente quando a coleta automatizada e outras fontes estiverem indisponíveis.','Úsalo solo cuando la recopilación automática y otras fuentes no estén disponibles.'], manualSaved:['Manual observation saved and available to live analytics.','Observação manual salva e disponível nas análises ao vivo.','Observación manual guardada y disponible en los análisis en vivo.'],
  dataReview:['Data review','Revisão de dados','Revisión de datos'], recentObservations:['Recent observations','Observações recentes','Observaciones recientes'], latestRecords:['Latest 150 records','Últimos 150 registros','Últimos 150 registros'], filterAttraction:['Filter attraction','Filtrar atração','Filtrar atracción'], allAttractions:['All attractions','Todas as atrações','Todas las atracciones'], observed:['Observed','Observado','Observado'], queue:['Queue','Fila','Fila'], actions:['Actions','Ações','Acciones'], valid:['Valid','Válida','Válida'], invalid:['Invalid: {reason}','Inválida: {reason}','No válida: {reason}'], invalidate:['Invalidate','Invalidar','Invalidar'], restore:['Restore','Restaurar','Restaurar'], invalidReason:['Reason for invalidation','Motivo da invalidação','Motivo de invalidación'], confirmInvalidation:['Confirm invalidation','Confirmar invalidação','Confirmar invalidación'], cancel:['Cancel','Cancelar','Cancelar'],
  permanentDeletion:['Permanent data deletion','Exclusão permanente de dados','Eliminación permanente de datos'], deletionHelp:['Permanently remove observations in a specific time range. Invalidating records is safer and should be preferred.','Remova permanentemente observações em um período específico. Invalidar registros é mais seguro e deve ser preferido.','Elimina permanentemente observaciones en un período específico. Invalidar registros es más seguro y debe preferirse.'], from:['From','De','Desde'], to:['To','Até','Hasta'], typeDelete:['Type DELETE to confirm','Digite DELETE para confirmar','Escribe DELETE para confirmar'], deleteObservations:['Permanently delete observations','Excluir observações permanentemente','Eliminar observaciones permanentemente'], deleted:['{count} observations deleted.','{count} observações excluídas.','{count} observaciones eliminadas.'], diagnostics:['Diagnostics','Diagnóstico','Diagnóstico'], recentAttempts:['Most recent 100 attempts','100 tentativas mais recentes','100 intentos más recientes'], started:['Started','Início','Inicio'], result:['Result','Resultado','Resultado'], error:['Error','Erro','Error'], retry:['Retry','Tentar novamente','Reintentar'], retrySuccess:['Collection retry completed successfully.','Nova tentativa de coleta concluída com sucesso.','Reintento de recopilación completado correctamente.'], mutationError:['Request failed: {message}','Falha na solicitação: {message}','Error en la solicitud: {message}'],
} as const

export type TranslationKey = keyof typeof messages
export type Translate = (key: TranslationKey, values?: Record<string, string | number>) => string
const localeIndex: Record<Locale, 0 | 1 | 2> = { en: 0, 'pt-BR': 1, es: 2 }
const STORAGE_KEY = 'park-pilot-locale'
function resolveLocale(): Locale {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (supportedLocales.includes(stored as Locale)) return stored as Locale
  } catch {
    // Storage can be unavailable in privacy-restricted browser contexts.
  }
  for (const language of navigator.languages ?? [navigator.language]) {
    const value = language.toLowerCase()
    if (value.startsWith('pt')) return 'pt-BR'
    if (value.startsWith('es')) return 'es'
    if (value.startsWith('en')) return 'en'
  }
  return 'en'
}
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey, values?: Record<string, string | number>) => string }
const I18nContext = createContext<I18nValue | null>(null)
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(resolveLocale)
  useEffect(() => {
    document.documentElement.lang = locale
    document.title = messages.appTitle[localeIndex[locale]]
    try {
      localStorage.setItem(STORAGE_KEY, locale)
    } catch {
      // Keep the selected locale for this session when persistence is unavailable.
    }
  }, [locale])
  const t: I18nValue['t'] = (key, values) => {
    let text: string = messages[key][localeIndex[locale]]
    for (const [name, value] of Object.entries(values ?? {})) text = text.replaceAll(`{${name}}`, String(value))
    return text
  }
  return <I18nContext value={{ locale, setLocale, t }}>{children}</I18nContext>
}
export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('Missing I18nProvider'); return value }
export function LanguageSelector() {
  const { locale, setLocale, t } = useI18n()
  return <label className="language-selector"><span>{t('language')}</span><select aria-label={t('language')} value={locale} onChange={(event) => setLocale(event.target.value as Locale)}><option value="en">{t('english')}</option><option value="pt-BR">{t('portuguese')}</option><option value="es">{t('spanish')}</option></select></label>
}