import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'

export const supportedLocales = ['en', 'pt-BR', 'es'] as const
export type Locale = (typeof supportedLocales)[number]

const messages = {
  language:['Language','Idioma','Idioma'], english:['English','English','English'], portuguese:['Português (Brasil)','Português (Brasil)','Português (Brasil)'], spanish:['Español','Español','Español'], appTitle:['Park Queue Intelligence','Inteligência de Filas dos Parques','Inteligencia de Filas de Parques'],
  home:['Park Queue Intelligence home','Início do Park Queue Intelligence','Inicio de Park Queue Intelligence'], brand:['Queue Intelligence','Queue Intelligence','Queue Intelligence'], parkOperations:['Park operations','Operações do parque','Operaciones del parque'], administration:['Administration','Administração','Administración'], visitorDashboard:['Visitor dashboard','Painel do visitante','Panel de visitantes'], serviceOnline:['Data service online','Serviço de dados online','Servicio de datos en línea'],
  liveOperations:['Live operations','Operações ao vivo','Operaciones en vivo'], waitTimes:['Attraction wait times','Tempos de espera das atrações','Tiempos de espera de atracciones'], dashboardDescription:['Monitor current queues and compare three months of historical patterns.','Monitore as filas atuais e compare três meses de padrões históricos.','Supervisa las filas actuales y compara tres meses de patrones históricos.'], viewingPark:['Viewing park','Parque exibido','Parque mostrado'], parkSummary:['Park summary','Resumo do parque','Resumen del parque'], trackedAttractions:['Tracked attractions','Atrações monitoradas','Atracciones supervisadas'], currentlyOpen:['Currently open','Abertas agora','Abiertas ahora'], averageCurrentWait:['Average current wait','Espera média atual','Espera promedio actual'], parkTimezone:['Park timezone','Fuso horário do parque','Zona horaria del parque'],
  dailyComparison:['Daily park comparison','Comparação diária dos parques','Comparación diaria de parques'], averageEachPark:['Average wait across each park','Espera média em cada parque','Espera promedio en cada parque'], dailyDescription:['Each attraction contributes one daily average, regardless of sample count.','Cada atração contribui com uma média diária, independentemente do número de amostras.','Cada atracción aporta un promedio diario, sin importar la cantidad de muestras.'], currentWeek:['Current week','Semana atual','Semana actual'], selectWeek:['Select comparison week','Selecionar semana de comparação','Seleccionar semana de comparación'], previousWeek:['View previous week','Ver semana anterior','Ver semana anterior'], nextWeek:['View next week','Ver próxima semana','Ver semana siguiente'],
  currentConditions:['Current conditions','Condições atuais','Condiciones actuales'], attractionQueues:['Attraction queues','Filas das atrações','Filas de atracciones'], live:['Live','Ao vivo','En vivo'], updated:['Updated {date}','Atualizado em {date}','Actualizado {date}'], filterQueues:['Filter attraction queues','Filtrar filas das atrações','Filtrar filas de atracciones'], land:['Land','Área','Área'], filterLand:['Filter attractions by land','Filtrar atrações por área','Filtrar atracciones por área'], allLands:['All lands','Todas as áreas','Todas las áreas'], attractionName:['Attraction name','Nome da atração','Nombre de la atracción'], filterName:['Filter attractions by name','Filtrar atrações por nome','Filtrar atracciones por nombre'], searchAttractions:['Search attractions','Buscar atrações','Buscar atracciones'], attraction:['Attraction','Atração','Atracción'], wait:['Wait','Espera','Espera'], parkWide:['Park-wide','Todo o parque','Todo el parque'], closed:['Closed','Fechada','Cerrada'], min:['min','min','min'],
  threeMonthTrend:['Three-month trend','Tendência de três meses','Tendencia de tres meses'], selectAttraction:['Select an attraction','Selecione uma atração','Selecciona una atracción'], dailyHistoryAria:['Daily wait-time history for {name}','Histórico diário de espera de {name}','Historial diario de espera de {name}'], typicalDemand:['Typical demand','Demanda típica','Demanda típica'], waitByWeekday:['Wait by weekday and time','Espera por dia e horário','Espera por día y hora'], averages15:['15-minute averages','Médias de 15 minutos','Promedios de 15 minutos'], patternAria:['Average waits by weekday and time for {name}','Esperas médias por dia e horário de {name}','Esperas promedio por día y hora de {name}'], dailyParkAria:['Daily average park wait times from {start} through {end}','Tempos médios diários de espera de {start} até {end}','Tiempos de espera diarios promedio del {start} al {end}'],
  loadingParks:['Loading park intelligence...','Carregando informações dos parques...','Cargando información de parques...'], catalogUnavailable:['The park catalog is unavailable.','O catálogo de parques está indisponível.','El catálogo de parques no está disponible.'], preparingChart:['Preparing chart...','Preparando gráfico...','Preparando gráfico...'], loadingAnalytics:['Loading analytics...','Carregando análises...','Cargando análisis...'], analyticsUnavailable:['Analytics could not be loaded.','Não foi possível carregar as análises.','No se pudieron cargar los análisis.'], notEnoughData:['Not enough observations are available yet.','Ainda não há observações suficientes.','Aún no hay suficientes observaciones.'], currentWaitsUnavailable:['Current waits could not be loaded.','Não foi possível carregar as esperas atuais.','No se pudieron cargar las esperas actuales.'], noObservations:['No attraction observations are available yet.','Ainda não há observações de atrações.','Aún no hay observaciones de atracciones.'], noFilterMatches:['No attractions match the selected filters.','Nenhuma atração corresponde aos filtros.','Ninguna atracción coincide con los filtros.'], loadingWaits:['Loading current attraction waits','Carregando esperas atuais','Cargando esperas actuales'], connectionError:['Connection error','Erro de conexão','Error de conexión'], pleaseWait:['Please wait','Aguarde','Espera'],
  averageMinutes:['Average minutes','Média em minutos','Promedio en minutos'], minutes:['Minutes','Minutos','Minutos'], dailyAverage:['Daily average','Média diária','Promedio diario'], dailyMaximum:['Daily maximum','Máximo diário','Máximo diario'], averageWait:['Average wait','Espera média','Espera promedio'], attractionsCount:['{count} attractions','{count} atrações','{count} atracciones'], samplesCount:['{count} samples','{count} amostras','{count} muestras'], sunday:['Sunday','Domingo','Domingo'], monday:['Monday','Segunda-feira','Lunes'], tuesday:['Tuesday','Terça-feira','Martes'], wednesday:['Wednesday','Quarta-feira','Miércoles'], thursday:['Thursday','Quinta-feira','Jueves'], friday:['Friday','Sexta-feira','Viernes'], saturday:['Saturday','Sábado','Sábado'],
  operationsTooling:['Operations tooling','Ferramentas operacionais','Herramientas operativas'], adminDescription:['Maintain catalog data, monitor collection health, and manage queue observations.','Mantenha os dados do catálogo, monitore a coleta e gerencie observações de filas.','Mantén los datos del catálogo, supervisa la recopilación y administra observaciones de filas.'], workingPark:['Working park','Parque em edição','Parque en edición'], addPark:['Add park','Adicionar parque','Agregar parque'], adminSections:['Administration sections','Seções de administração','Secciones de administración'], operations:['Operations','Operações','Operaciones'], catalog:['Catalog','Catálogo','Catálogo'], observations:['Observations','Observações','Observaciones'], collectionRuns:['Collection runs','Execuções de coleta','Ejecuciones de recopilación'], loadingAdmin:['Loading administration data...','Carregando dados administrativos...','Cargando datos administrativos...'], adminUnavailable:['Administration data could not be loaded.','Não foi possível carregar os dados administrativos.','No se pudieron cargar los datos administrativos.'],
  catalogSetup:['Catalog setup','Configuração do catálogo','Configuración del catálogo'], addSupportedPark:['Add supported park','Adicionar parque compatível','Agregar parque compatible'], externalQueueId:['Use the external Queue-Times park identifier','Use o identificador externo do parque no Queue-Times','Usa el identificador externo del parque en Queue-Times'], parkName:['Park name','Nome do parque','Nombre del parque'], externalParkId:['External park ID','ID externo do parque','ID externo del parque'], timezone:['Timezone','Fuso horário','Zona horaria'], collectionInterval:['Collection interval','Intervalo de coleta','Intervalo de recopilación'], minutesWord:['minutes','minutos','minutos'], startAutomatic:['Start automatic collection','Iniciar coleta automática','Iniciar recopilación automática'], parkActive:['Park visible and active','Parque visível e ativo','Parque visible y activo'], addingPark:['Adding park...','Adicionando parque...','Agregando parque...'],
  collectionHealth:['Collection health','Saúde da coleta','Estado de recopilación'], attentionRequired:['Attention required','Atenção necessária','Requiere atención'], collectionActive:['Collection active','Coleta ativa','Recopilación activa'], collectionPaused:['Collection paused','Coleta pausada','Recopilación pausada'], attractions:['Attractions','Atrações','Atracciones'], lastAttempt:['Last attempt','Última tentativa','Último intento'], lastResult:['Last result','Último resultado','Último resultado'], noRuns:['No runs','Nenhuma execução','Sin ejecuciones'], successful:['Successful','Bem-sucedida','Correcto'], failed:['Failed','Falhou','Fallido'], collecting:['Collecting...','Coletando...','Recopilando...'], collectNow:['Collect now','Coletar agora','Recopilar ahora'], collectHelp:['Runs immediately without changing the automatic schedule.','Executa imediatamente sem alterar a programação automática.','Se ejecuta de inmediato sin cambiar la programación automática.'], configuration:['Configuration','Configuração','Configuración'], parkSettings:['Park settings','Configurações do parque','Configuración del parque'], automaticCollection:['Automatic collection','Coleta automática','Recopilación automática'], saving:['Saving...','Salvando...','Guardando...'], saveSettings:['Save settings','Salvar configurações','Guardar configuración'], parkSaved:['Park settings saved.','Configurações do parque salvas.','Configuración del parque guardada.'], collectionSuccess:['Collection completed successfully.','Coleta concluída com sucesso.','Recopilación completada correctamente.'], never:['Never','Nunca','Nunca'],
  parkStructure:['Park structure','Estrutura do parque','Estructura del parque'], lands:['Lands','Áreas','Áreas'], configured:['{count} configured','{count} configurados','{count} configurados'], addLandPlus:['+ Add land','+ Adicionar área','+ Agregar área'], manualCatalogEntry:['Create a manual catalog entry','Criar uma entrada manual no catálogo','Crear una entrada manual en el catálogo'], source:['Source','Origem','Origen'], active:['Active','Ativo','Activo'], inactive:['Inactive','Inativo','Inactivo'], landName:['Land name','Nome da área','Nombre del área'], externalLandId:['External land ID','ID externo da área','ID externo del área'], landActive:['Land active','Área ativa','Área activa'], saveLand:['Save land','Salvar área','Guardar área'], addLand:['Add land','Adicionar área','Agregar área'], queueCatalog:['Queue catalog','Catálogo de filas','Catálogo de filas'], addAttractionPlus:['+ Add attraction','+ Adicionar atração','+ Agregar atracción'], externalAttractionId:['External attraction ID','ID externo da atração','ID externo de la atracción'], duration:['Duration','Duração','Duración'], latitude:['Latitude','Latitude','Latitud'], longitude:['Longitude','Longitude','Longitud'], attractionActive:['Attraction active','Atração ativa','Atracción activa'], saveAttraction:['Save attraction','Salvar atração','Guardar atracción'], addAttraction:['Add attraction','Adicionar atração','Agregar atracción'],
  lastResort:['Last-resort fallback','Alternativa de último recurso','Alternativa de último recurso'], enterObservation:['Enter queue observation manually','Inserir observação de fila manualmente','Ingresar observación de fila manualmente'], auditableRun:['Creates an auditable manual collection run','Cria uma execução manual auditável','Crea una ejecución manual auditable'], selectAttractionOption:['Select attraction','Selecione a atração','Selecciona la atracción'], observedAt:['Observed at','Observado em','Observado el'], status:['Status','Status','Estado'], open:['Open','Aberta','Abierta'], waitTime:['Wait time','Tempo de espera','Tiempo de espera'], saveObservation:['Save observation','Salvar observação','Guardar observación'], manualHelp:['Use only when automated collection and other sources are unavailable.','Use somente quando a coleta automatizada e outras fontes estiverem indisponíveis.','Úsalo solo cuando la recopilación automática y otras fuentes no estén disponibles.'], manualSaved:['Manual observation saved and available to live analytics.','Observação manual salva e disponível nas análises ao vivo.','Observación manual guardada y disponible en los análisis en vivo.'],
  dataReview:['Data review','Revisão de dados','Revisión de datos'], recentObservations:['Recent observations','Observações recentes','Observaciones recientes'], latestRecords:['Latest 150 records','Últimos 150 registros','Últimos 150 registros'], filterAttraction:['Filter attraction','Filtrar atração','Filtrar atracción'], allAttractions:['All attractions','Todas as atrações','Todas las atracciones'], observed:['Observed','Observado','Observado'], queue:['Queue','Fila','Fila'], actions:['Actions','Ações','Acciones'], valid:['Valid','Válida','Válida'], invalid:['Invalid: {reason}','Inválida: {reason}','No válida: {reason}'], invalidate:['Invalidate','Invalidar','Invalidar'], restore:['Restore','Restaurar','Restaurar'], invalidReason:['Reason for invalidation','Motivo da invalidação','Motivo de invalidación'], confirmInvalidation:['Confirm invalidation','Confirmar invalidação','Confirmar invalidación'], cancel:['Cancel','Cancelar','Cancelar'],
  permanentDeletion:['Permanent data deletion','Exclusão permanente de dados','Eliminación permanente de datos'], deletionHelp:['Permanently remove observations in a specific time range. Invalidating records is safer and should be preferred.','Remova permanentemente observações em um período específico. Invalidar registros é mais seguro e deve ser preferido.','Elimina permanentemente observaciones en un período específico. Invalidar registros es más seguro y debe preferirse.'], from:['From','De','Desde'], to:['To','Até','Hasta'], typeDelete:['Type DELETE to confirm','Digite DELETE para confirmar','Escribe DELETE para confirmar'], deleteObservations:['Permanently delete observations','Excluir observações permanentemente','Eliminar observaciones permanentemente'], deleted:['{count} observations deleted.','{count} observações excluídas.','{count} observaciones eliminadas.'], diagnostics:['Diagnostics','Diagnóstico','Diagnóstico'], recentAttempts:['Most recent 100 attempts','100 tentativas mais recentes','100 intentos más recientes'], started:['Started','Início','Inicio'], result:['Result','Resultado','Resultado'], error:['Error','Erro','Error'], retry:['Retry','Tentar novamente','Reintentar'], retrySuccess:['Collection retry completed successfully.','Nova tentativa de coleta concluída com sucesso.','Reintento de recopilación completado correctamente.'], mutationError:['Request failed: {message}','Falha na solicitação: {message}','Error en la solicitud: {message}'],
} as const

export type TranslationKey = keyof typeof messages
export type Translate = (key: TranslationKey, values?: Record<string, string | number>) => string
const localeIndex: Record<Locale, 0 | 1 | 2> = { en: 0, 'pt-BR': 1, es: 2 }
const STORAGE_KEY = 'park-pilot-locale'
function resolveLocale(): Locale {
  try {
    const stored = localStorage.getItem(STORAGE_KEY)
    if (supportedLocales.includes(stored as Locale)) return stored as Locale
  } catch {
    // Storage can be unavailable in privacy-restricted browser contexts.
  }
  for (const language of navigator.languages ?? [navigator.language]) {
    const value = language.toLowerCase()
    if (value.startsWith('pt')) return 'pt-BR'
    if (value.startsWith('es')) return 'es'
    if (value.startsWith('en')) return 'en'
  }
  return 'en'
}
type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey, values?: Record<string, string | number>) => string }
const I18nContext = createContext<I18nValue | null>(null)
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(resolveLocale)
  useEffect(() => {
    document.documentElement.lang = locale
    document.title = messages.appTitle[localeIndex[locale]]
    try {
      localStorage.setItem(STORAGE_KEY, locale)
    } catch {
      // Keep the selected locale for this session when persistence is unavailable.
    }
  }, [locale])
  const t: I18nValue['t'] = (key, values) => {
    let text: string = messages[key][localeIndex[locale]]
    for (const [name, value] of Object.entries(values ?? {})) text = text.replaceAll(`{${name}}`, String(value))
    return text
  }
  return <I18nContext value={{ locale, setLocale, t }}>{children}</I18nContext>
}
export function useI18n() { const value = useContext(I18nContext); if (!value) throw new Error('Missing I18nProvider'); return value }
export function LanguageSelector() {
  const { locale, setLocale, t } = useI18n()
  return <label className="language-selector"><span>{t('language')}</span><select aria-label={t('language')} value={locale} onChange={(event) => setLocale(event.target.value as Locale)}><option value="en">{t('english')}</option><option value="pt-BR">{t('portuguese')}</option><option value="es">{t('spanish')}</option></select></label>
}